const GET_SELLER = "GET_SELLER";
const GET_GOODS = "GET_GOODS";
const GET_RATINGS = "GET_RATINGS";
const GET_GETTERS = "GET_GETTERS";
const SHOW_SELLER_DETAIL = "SHOW_SELLER_DETAIL";
const HIDE_SELLER_DETAIL = "HIDE_SELLER_DETAIL";

const SHOW_FOOD_DETAIL = "SHOW_FOOD_DETAIL";
const HIDE_FOOD_DETAIL = "HIDE_FOOD_DETAIL";
export default {
	GET_SELLER,
	GET_GOODS,
	GET_RATINGS,
	GET_GETTERS,
	SHOW_SELLER_DETAIL,
	HIDE_SELLER_DETAIL,

	SHOW_FOOD_DETAIL,
	HIDE_FOOD_DETAIL
}